### ISSUE TITLE
Using Emscripten upstream version isn't working

### ISSUE THREAD

**Issue by ThorstenBux** [kalwalt/jsartoolkit5#10]
I just want to note that to not forget. I've build with emscripten-upstream and ran into these issues:

1. LibJPEG from your libJPEG repo isn't working. I think that is to be expected because your version of libJPEG is build with fastcomp.

1. Runtime error because memory growth isn't allowed. That can be fixed by adding 
`FLAGS += ' -s ALLOW_MEMORY_GROWTH=1 '` to makeem.js which we could add per default anyways.

2. Runtime error when copying the JS video stream image to C++ compile code.
```
Uncaught TypeError: Cannot perform %TypedArray%.prototype.set on a detached ArrayBuffer
    at Uint8Array.set (<anonymous>)
    at ARController._copyImageToHeap (VM44 artoolkit_wasm.js:1)
    at ARController.detectMarker (VM44 artoolkit_wasm.js:1)
    at ARController.process (VM44 artoolkit_wasm.js:1)
    at Object.process (VM54 artoolkit.three.js:152)
    at tick (nft_threejs_wasm.html:96)
```

I didn't follow this bug till the end, hence this note to keep it in mind.

**Comment by ThorstenBux** [comment]
This might fix it. It seems to be memory growth related" https://github.com/emscripten-core/emscripten/issues/6747

**Comment by ThorstenBux** [comment]
Update: it is not `upstream` related I get it on `fastcomp` too

**Comment by ThorstenBux** [comment]
I tracked this down to be a wasm issue. Maybe only on macos Chrome as you haven't noticed it so far. 

I fixed the memory growth and the TypeError now I'm getting
```
Uncaught RuntimeError: float unrepresentable in integer range
    at wasm-function[176]:0x77e7
    at wasm-function[949]:0x3ee6a
    at wasm-function[950]:0x3eebe
    at wasm-function[951]:0x3f033
    at wasm-function[952]:0x3f17e
    at wasm-function[1070]:0x46410
    at wasm-function[1027]:0x445f8
    at wasm-function[1028]:0x446f2
    at wasm-function[1029]:0x44722
    at wasm-function[1178]:0x4fdfd
```
which might be fixable by `trap` mode: https://emscripten.org/docs/compiling/WebAssembly.html

**Comment by ThorstenBux** [comment]
The none wasm examples work (build and run successfully) with memory_growth enabled. I haven't printed the pinball marker yet.

**Comment by ThorstenBux** [comment]
getting `[error] Out of memory!!` on Safary iOS

**Comment by ThorstenBux** [comment]
WIP branch: https://github.com/ThorstenBux/jsartoolkit5/tree/thorsten/build-script

**Comment by kalwalt** [comment]
@ThorstenBux i switched to an older Emscripten version, because you and @nicolocarpignoli used this. But sure better use the latest with upstream. Recently. I did a node script to build the libjpeg.bc by yourself https://github.com/kalwalt/libjpeg-for-jsartoolkit5/blob/master/tools/makem.js in this day you can build your own libjpeg.
About Allow Memory growth, wasn't already enabled? 
Yes the trap mode should solve the wasm issue, strange that you get that error though... I Will look Into your branch this afternoon. Thanks ! ☺️

**Comment by ThorstenBux** [comment]
Currently I'm having issues with upstream and fastcomp. I guess it is because of the version but still need to verify.

**Comment by ThorstenBux** [comment]
@kalwalt the issue is that even if I just use the committed, pre-build libs I can't run the NFT wasm examples successfully.

**Comment by kalwalt** [comment]
Pay attention that changing emscripten version you need to clear the emscripten cache.

**Comment by kalwalt** [comment]
> @kalwalt the issue is that even if I just use the committed, pre-build libs I can't run the NFT wasm examples successfully.

No, with the prebuild libjpeg.bc and the emscripten fastcomp you Will get the wasm error. I think It works only with latest upstream emscripten.

**Comment by kalwalt** [comment]
i'm testing your branch, i see that examples are not NFT examplestracking properly. Maybe because was removed the `'use strict'`?

**Comment by kalwalt** [comment]
@ThorstenBux It was removed with this commit https://github.com/kalwalt/jsartoolkit5/pull/1/commits/a91d8bd4537542b25979b155fc082fce54cd79f3 try to add it again and let me know.

**Comment by kalwalt** [comment]
i opened this issue #11 for anyone has some troubles and problems with Emscripten.

**Comment by ThorstenBux** [comment]
Closing because this is fixed with Docker setup
