### ISSUE TITLE
How to configure Emscripten for jsartoolkit5

### ISSUE THREAD

**Issue by kalwalt** [kalwalt/jsartoolkit5#11]
# Emscripten for jsartoolkit5
In this issue i want to explain how to setup Emscripten for jsartoolkit5. Because we had a certain number of issue compiling in different OS and sharing the code, compiled with different Emscripten versions. 
Be aware that now Emscripten may use two different backends for emitting WASM code as described here https://emscripten.org/docs/compiling/WebAssembly.html#backends read carefully this because using a different backends lead to errors if you want to recompile it with a different backend.
If you want change the WASM backend or the Emscripten version consider that the **makem.js** https://github.com/kalwalt/jsartoolkit5/blob/fa15cb1e128c91a714d31152081083796133c3a1/tools/makem.js#L19 use the emscripten environment variable, if you switch form upstream to fastcomp you need to change it !! 
## Setting the paths
Infact they are separate folder for **upstream** the path should looks like:

`/path/to/emsdk/upstream/emscripten/`

for **fastcomp**:

`/path/to/emsdk/fastcomp/emscripten`

and so the environment variable should be (for fastcomp):

`export EMSCRIPTEN=/home/walter/emsdk/fastcomp/emscripten
`
while changing version/backend remember to clear the Emscripten cache:

`emcc --clear-cache`

## Final summary

Use the Emscripten version recommended in the https://github.com/kalwalt/jsartoolkit5/pull/1#issue-282747579 if you have a different one make these steps:

- install the Emscripten version required:

`./emsdk install 1.xx.xx-fastcomp
`

- activate it 

`./emsdk activate 1.xx.xx-fastcomp`

- activate path and other env vars

`source ./emsdk_env.sh`

- change your emescripten var as explained above !!

- clear the emscripten cache:

`emcc --clear-cache`

-  now you can rebuild the jsartoolkit5 libs:

```js
// inside the jsartoolkit5 folder run as usual:
npm run build
```

Anyway hopefully soon we will setup a Docker environment to solve most of these issues.

#### Update
We strongly suggest to use Docker to build the project as written in the README.md https://github.com/kalwalt/jsartoolkit5/tree/fixing-nft#recommended-build-using-docker

**Comment by ThorstenBux** [comment]
plain clone of the fixing-nft branch

macos zsh
```
thorstenbux@Zaphod jsartoolkit5 % emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.5
clang version 6.0.1 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-emscripten--core-emscripten--fastcomp--clang 98df4be387dde3e3918fa5bbb5fc43e1a0e1daac) (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-emscripten--core-emscripten--fastcomp b4837f88af2d240abb550c0bbd47f3b8ffe5985a) (emscripten 1.38.31 : 1.38.31)
Target: x86_64-apple-darwin19.2.0
Thread model: posix
InstalledDir: /Users/thorstenbux/repos/emsdk/fastcomp/fastcomp/bin
shared:INFO: (Emscripten: Running sanity checks)
thorstenbux@Zaphod jsartoolkit5 % echo $EMSCRIPTEN
/Users/thorstenbux/repos/emsdk/fastcomp/emscripten
thorstenbux@Zaphod jsartoolkit5 % emcc --clear-cache
emcc:INFO: clearing cache as requested by --clear-cache
shared:INFO: (Emscripten: Running sanity checks)
```

`npm run build`

running locally with `http-server -S -C` and self-signed certificates.

Errors:
*https://192.168.1.3:8080/examples/nft_improved_worker/nft_pinball_video.html*
`artoolkit.min.js:1 Uncaught abort(OOM). Build with -s ASSERTIONS=1 for more info.`

*https://192.168.1.3:8080/examples/nft_threejs_wasm.html*
`Uncaught RuntimeError: abort(OOM). Build with -s ASSERTIONS=1 for more info.`

**Comment by ThorstenBux** [comment]
Falling back to **1.38.44-fastcomp**

`install 1.38.44-fastcomp`
`activate 1.38.44-fastcomp`
`source ./emsdk_env.sh`

Restarted all active Terminals
Restarted VS code

```
thorstenbux@Zaphod ~ % emcc --clear-cache
emcc:INFO: clearing cache as requested by --clear-cache
shared:INFO: (Emscripten: Running sanity checks)

thorstenbux@Zaphod ~ % emcc -v
cache:INFO: generating system asset: is_vanilla.txt... (this will be cached in "/Users/thorstenbux/.emscripten_cache/is_vanilla.txt" for subsequent builds)
cache:INFO:  - ok
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.44
clang version 6.0.1 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-emscripten--core-emscripten--fastcomp--clang 98df4be387dde3e3918fa5bbb5fc43e1a0e1daac) (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-emscripten--core-emscripten--fastcomp 1b4148f39a69c7fc62edadd85e4122b68694dfb7) (emscripten 1.38.31 : 1.38.31)
Target: x86_64-apple-darwin19.2.0
Thread model: posix
InstalledDir: /Users/thorstenbux/repos/emsdk/fastcomp/fastcomp/bin
shared:INFO: (Emscripten: Running sanity checks)

thorstenbux@Zaphod ~ % echo $EMSCRIPTEN
/Users/thorstenbux/repos/emsdk/fastcomp/emscripten
```

`npm run build`

Errors:
*examples/nft_threejs_wasm.html*
`Uncaught abort(OOM). Build with -s ASSERTIONS=1 for more info.`

*examples/nft_improved_worker/nft_pinball_video.html*
`Uncaught abort(OOM). Build with -s ASSERTIONS=1 for more info.`

**Comment by ThorstenBux** [comment]
Conclusion:

I think it is safe to assume it doesn't build with **NFT** on macOS

**Comment by kalwalt** [comment]
@ThorstenBux that Is weird! And It looks very strange, i will think about it. Thank you for testing ☺️.

**Comment by ThorstenBux** [comment]
I'm setting up docker now. How do you install libJPEG on your linux box? I need it for the includes

**Comment by kalwalt** [comment]
My libjpeg  includes are in  **emscripten/libjpeg** folder.

**Comment by ThorstenBux** [comment]
did you put them there? I can't find them in my emscripten installation

**Comment by ThorstenBux** [comment]
never mind. I think I've got a docker setup working. Will test in details tomorrow and push to a branch

**Comment by ThorstenBux** [comment]
@kalwalt Happy New Year :)

plz have a look if that works for you. The instructions on how to build with Docker are in the readme
https://github.com/ThorstenBux/jsartoolkit5/tree/build-with-docker

If you say it is working I'll open a PR.

**Comment by kalwalt** [comment]
@ThorstenBux Happy New Year!! Sorry was very late, i will test your branch

**Comment by kalwalt** [comment]
About libjpeg includes i take them from https://github.com/kalwalt/libjpeg-for-jsartoolkit5

**Comment by kalwalt** [comment]
@ThorstenBux i tested your branch https://github.com/ThorstenBux/jsartoolkit5/tree/build-with-docker and it works pefectly for me.  If you open a PR i will review you.

**Comment by kalwalt** [comment]
It is reccomended to use the Docker setup see in the Readme.md https://github.com/kalwalt/jsartoolkit5/tree/fixing-nft#recommended-build-using-docker

**Comment by nicolocarpignoli** [comment]
I think we can close this, right?

**Comment by ThorstenBux** [comment]
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
