### ISSUE TITLE
Enhance loader time of disappearing at initial loading

### ISSUE THREAD

**Issue by kalwalt** [kalwalt/jsartoolkit5#15]
I leave this as a remider for you @nicolocarpignoli.

**Comment by nicolocarpignoli** [comment]
fixed. the event is firing with right times (at least for me), and as soon as the message is received, the loader is removed.

Can you please test the threejs_worker_gltf.html example? If it's working also for you, I will close this one.

**Comment by kalwalt** [comment]
i tested yes it' is ok for me.
