### ISSUE TITLE
Adding tests for NFT

### ISSUE THREAD

**Issue by kalwalt** [kalwalt/jsartoolkit5#20]
We need to add tests for the NFT. @ThorstenBux May you help me?

**Comment by ThorstenBux** [comment]
Yes, I still have that on my radar. Will look into that tomorrow.

**Comment by ThorstenBux** [comment]
PR opened

**Comment by kalwalt** [comment]
Thank you @ThorstenBux !

**Comment by ThorstenBux** [comment]
Could you look at tests for wasm?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kalwalt** [comment]
@ThorstenBux i will see what can i do!

**Comment by kalwalt** [comment]
Done with #21
