### ISSUE TITLE
Add aframe example

### ISSUE THREAD

**Issue by nicolocarpignoli** [kalwalt/jsartoolkit5#23]
It could be useful to add an example using aframe like it was done for the threejs + gltf.

**Comment by nicolocarpignoli** [comment]
Removing from project, this is not mandatory but instead a nice to have.

**Comment by kalwalt** [comment]
It would be nice Indeed, if we have time we can add It. Sorry, i am a Three.js fan, haven't thought to use other 3d frameworks. Litescene.js is also interesting and has a nice editor too....

**Comment by nicolocarpignoli** [comment]
yes, my idea is for now to add aframe and threejs to then integrate faster with ar.js.

**Comment by nicolocarpignoli** [comment]
this one will be added directly on AR.js for now.
