### ISSUE TITLE
Switching to ES5 instead of ES6 standard in the NFT examples

### ISSUE THREAD

**Issue by kalwalt** [kalwalt/jsartoolkit5#27]
As pointed in this comment https://github.com/kalwalt/jsartoolkit5/pull/1#issuecomment-573000113 we should switch to ES5 standard.
If you find other code that use ES6 standard please leave me a note here.

**Comment by nicolocarpignoli** [comment]
done with https://github.com/kalwalt/jsartoolkit5/pull/1/commits/2103d756e6c0f5b8d3420dc62d5bddf1161ac6b7

if it's ok for you we can close this one :)

**Comment by kalwalt** [comment]
@nicolocarpignoli only one last thing: i commented in the code and after it is ok.

**Comment by kalwalt** [comment]
Perfect! we can close this now.
