### ISSUE TITLE
Issue with gltf model rendered completely black

### ISSUE THREAD

**Issue by kalwalt** [kalwalt/jsartoolkit5#29]
This issue happens while testing with my Android device a Wiko View model (Adreno Based cpu) the gltf example **threejs_worker_gltf.html**: The model appear black without color (it should be a pinky one). This issue is easy to fix just need to add a `precision: 'mediump'` in the renderer:

```diff
-let renderer = new THREE.WebGLRenderer({ canvas: canvas_draw, alpha: true, antialias: true});
+let renderer = new THREE.WebGLRenderer({ canvas: canvas_draw, alpha: true, antialias: true, precision: 'mediump' });
```
I have an example here where i add the same problem  https://kalwalt.github.io/kalwalt-interactivity-AR/nft/nft_duck.html if you want to test and i fixed adding this flag.
Probably some other users can have this issue, not sure if this change ( the mediump flag) may have other consequences. If someone may test the example above with different devices would be nice. 
Note: that example display the duck gltf yellow model.

**Comment by nicolocarpignoli** [comment]
This is an issue with the 'renderer' used by Three.js, not jsartoolkit5, so should not be an issue in my opinion.

We can add that option as default on the threejs_gltf example, and add a line of comment to specify the reason (and link this issue, that we should close after that).

@kalwalt

**Comment by kalwalt** [comment]
Yes @nicolocarpignoli  this is a Three.js issue, i will add this option. I would only know if this option, in your opinion, may have other consequences on other devices, that's why i provided the link to test.

**Comment by nicolocarpignoli** [comment]
just tested, works good on the link, so no problem adding that parameter. I'm closing this one, and I have added the parameter with also the comment
