### ISSUE TITLE
Out of Memory issue using NFT

### ISSUE THREAD

**Issue by freeminders123** [kalwalt/jsartoolkit5#37]
Hi,
thanks for the great work! 
I've been testing the nft examples and wanted to use my own fset and iset files, which I created from a source image using genTexData.

But when I try to load them, it always logs [error] Out of memory!! from artoolkit_wasm.js in the console.
I am using Chrome on a Mac, but tested also with some mobile devices.

Do you have any suggestions on this topic?

The params I used for genTexData:

./genTexData fry_150.jpg -level=2 -leveli=2 -dpi=120 -min_dpi=120 -max_dpi=120

The original Image has 150 DPI at a size of 502x325 in RGB and is a Jpeg file.

I'm using the precompiled wasm file from the filtering_feature branch.
I added the original Image File and the generated fset and iset files as zip
[fset.zip](https://github.com/kalwalt/jsartoolkit5/files/4139821/fset.zip)

![fry_150](https://user-images.githubusercontent.com/11758859/73546727-fb6add80-443d-11ea-8aa7-7911f78dea89.jpg)

**Comment by kalwalt** [comment]
Ho @freeminders123 probably something wrong with the generated .fset files, i note that the image Is not so big in rispect of width and height dimensions. Instead oh using ./genTexData utility you can also try the online NFT Marker Generator https://carnaux.github.io/NFT-Marker-Creator/ as written in the [Readme.md](https://github.com/kalwalt/jsartoolkit5/blob/master/README.md) . I can't try your file now, but maybe i can later.

**Comment by freeminders123** [comment]
Hi @kalwalt thanks for the quick response. I just tried the linked creator but unfortunately with the same result.

**Comment by kalwalt** [comment]
@freeminders123 i will see, can you post also all the log if you can? And the other examples works fine for you?

**Comment by kalwalt** [comment]
Wait:  you say that you are you using my filtering branch? I do not recommend for now use the master branch instead.

**Comment by freeminders123** [comment]
The provided pinball example works as expected; Only my generated files do not work (tried with different images and different params);
Yes, I used the filtering branch as the tracking there is much better; But I tried the master branch too a couple of weeks ago with similar issues;
But I try again with the current master branch version and give you feedback.

I attached the error log here:
<img width="538" alt="Bildschirmfoto 2020-01-31 um 16 10 28" src="https://user-images.githubusercontent.com/11758859/73550067-34a64c00-4444-11ea-8f5c-386469cbe50a.png">

This is the complete log before the error is thrown:

<img width="538" alt="Bildschirmfoto 2020-01-31 um 16 11 16" src="https://user-images.githubusercontent.com/11758859/73550132-51428400-4444-11ea-8340-51e36054a82a.png">

**Comment by freeminders123** [comment]
@kalwalt Just tried the current master branch. This gives the same result and throws out of memory error.

**Comment by kalwalt** [comment]
I will test your files, and after i will let you know. :slightly_smiling_face:

**Comment by kalwalt** [comment]
@freeminders123 I tested your files and for me works quite well on my Desktop machine, i don't receive any errors and i am surprised because the size of the image. 
i tested the main_threejs_worker.html example with threejs_worker.js, i have only modified the url in the markers obj.
I tested with linux 64 bit Ubuntu 18.04.3 LTS and the Chrome browser v. 79.0.3945.79.
I would test tomorrow also with my Smartphone to see if raise an issue. Maybe this issue is related in some way to the browser?

**Comment by kalwalt** [comment]
I did also a quick test with the WASM version and it works fine too for me. 

**EDIT**: for both tests i used  the code from the master branch.

**Comment by kalwalt** [comment]
i also can see from your log output that are involved other .js files, maybe those files interfere in some way with the loading?

**Comment by freeminders123** [comment]
Thanks for your updates; I tested some of the files again with your master branch and also with the filtering-feature branch; They seem to work there on my machine; I take a look at the other scripts and see if I find something; 

I'll get back to this thread as soon as I found the problem

**Comment by freeminders123** [comment]
@kalwalt 
I couldn't reproduce this error anymore, seems to be a weird caching problem on my side; Now it works, thanks for your help;

By the way: Is there a possibility to get the center of the tracked marker? When I add the markerroot to the scene, it is always placed at the bottom left corner of the marker.

**Comment by kalwalt** [comment]
@freeminders123 glad that you solved this issue. At the moment Is not possible to fond the center of the NFT Marker, but we are working on this PR #42 . If you have not other questions related to this issue, i will close it.

**Comment by freeminders123** [comment]
@kalwalt Thanks for the info;
Yes, you can close this issue
